# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 20:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2016, 3, 4, 20, 25, 59, 920129, tzinfo=utc))),
            ],
            options={
                'ordering': ['datetime'],
                'verbose_name': 'Day',
                'verbose_name_plural': 'Days',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'Exercise', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.TextField()),
                ('day', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.Day')),
                ('exercise', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.Exercise')),
            ],
            options={
                'ordering': ['exercise', 'day'],
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
            },
        ),
        migrations.AlterUniqueTogether(
            name='training',
            unique_together=set([('exercise', 'day')]),
        ),
    ]
