# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=255)),
                ('target', models.CharField(choices=[(b'EM', b''), (b'BL', b'_blank'), (b'SF', b'_self'), (b'PR', b'_parent'), (b'TP', b'_top')], default=b'EM', max_length=2)),
                ('sort', models.PositiveIntegerField(default=100)),
                ('level', models.IntegerField(default=0)),
                ('for_staff', models.BooleanField(default=False)),
                ('subitems', models.ManyToManyField(blank=True, related_name='_menu_subitems_+', to='menu.Menu')),
            ],
            options={
                'ordering': ['sort'],
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
    ]
